quarkus.http.cors.enabled=true
quarkus.keycloak.devservices.port=9090




quarkus.langchain4j.mcp.customer.transport-type=streamable-http
quarkus.langchain4j.mcp.customer.url=http://localhost:8080/mcp

quarkus.oidc-client.auth-server-url=http://localhost:9090/auth/realms/quarkus
quarkus.oidc-client.credentials.secret=secret
quarkus.oidc-client.grant.type=password
quarkus.oidc-client.grant-options.password.username=alice
quarkus.oidc-client.grant-options.password.password=alice
