quarkus.http.port=7777
agent.url=${AGENT_URL:http://localhost:7777}
%test.agent.url=http://localhost:8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.max-size=16
%prod.quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/a2a}
%prod.quarkus.datasource.username=${DATABASE_USER:a2a}
%prod.quarkus.datasource.password=${DATABASE_PASSWORD:a2a}

quarkus.hibernate-orm."a2a-java".datasource=<default>
quarkus.hibernate-orm."a2a-java".database.generation=update
quarkus.hibernate-orm."a2a-java".log.sql=true
quarkus.hibernate-orm."a2a-java".packages=org.a2aproject.sdk.extras.taskstore.database.jpa,org.a2aproject.sdk.extras.pushnotificationconfigstore.database.jpa

%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.outgoing.replicated-events-out.connector=smallrye-kafka
mp.messaging.outgoing.replicated-events-out.topic=a2a-replicated-events
mp.messaging.outgoing.replicated-events-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer


mp.messaging.incoming.replicated-events-in.connector=smallrye-kafka
mp.messaging.incoming.replicated-events-in.topic=a2a-replicated-events

mp.messaging.incoming.replicated-events-in.group.id=a2a-cloud-${POD_NAME:local}
mp.messaging.incoming.replicated-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.replicated-events-in.auto.offset.reset=earliest